### PR TITLE
Added route publishing

### PR DESCRIPTION
**Pull request by mhtee**

### CODE REVIEW

**Comment by jordantaylor** [comment]
Nothing should be expecting x and y, as we are working strictly with lat and lon. Having any code relying on x and y would be confusing, so the x and y reliant code should instead be changed to reflect that these are lat and lng.

**Comment by mason-b** [comment]
My code is expecting x and y because that is how the client formatted the information. The only way to change the x and y to lat and lng would still be to be to write code the handles both names. Either that or asking the client to change the names from x and y to lat and lng.

**Comment by jordantaylor** [comment]
In that case it would be lat -> y, long -> x.

**Comment by mason-b** [comment]
My point is why write that extra code when we can just change the format.

**Comment by jordantaylor** [comment]
This PR needed to be modified to merge with my code that relies on it. I've made these changes as well as fixed the issue above in the branch jt-ma-merge, which I will PR.

**Comment by jordantaylor** [comment]
This PR needed to be modified to merge with my code that relies on it. I've made these changes as well as fixed the issue above in the branch jt-ma-merge, which I will PR.

**Pull request closed without merging**
